let produccionDeMantecaPorPais = [  
  { "nombre": "India", "iso3": "IND", "manteca": 4883981 },
  { "nombre": "Pakistán", "iso3": "PAK", "manteca": 1222785 },
  { "nombre": "Estados Unidos de América", "iso3": "USA", "manteca": 984271 },
  { "nombre": "Alemania", "iso3": "DEU", "manteca": 497300 },
  { "nombre": "Nueva Zelanda", "iso3": "NZL", "manteca": 483859 },
  { "nombre": "Francia", "iso3": "FRA", "manteca": 417540 },
  { "nombre": "Irlanda", "iso3": "IRL", "manteca": 293900 },
  { "nombre": "Turquía", "iso3": "TUR", "manteca": 270303 },
  { "nombre": "Federación Rusa", "iso3": "RUS", "manteca": 269216 },
  { "nombre": "Polonia", "iso3": "POL", "manteca": 243390 },
  { "nombre": "Países Bajos", "iso3": "NLD", "manteca": 220710 },
  { "nombre": "Irán", "iso3": "IRN", "manteca": 210024 },
  { "nombre": "Reino Unido", "iso3": "GBR", "manteca": 200000 },
  { "nombre": "Bélgica", "iso3": "BEL", "manteca": 122830 },
  { "nombre": "Bielorrusia", "iso3": "BLR", "manteca": 119530 },
  { "nombre": "Canadá", "iso3": "CAN", "manteca": 118235 },
  { "nombre": "Brasil", "iso3": "BRA", "manteca": 113000 },
  { "nombre": "República Popular China", "iso3": "CHN", "manteca": 98294 },
  { "nombre": "Egipto", "iso3": "EGY", "manteca": 97714 },
  { "nombre": "Uzbekistán", "iso3": "UZB", "manteca": 95822 },
  { "nombre": "Italia", "iso3": "ITA", "manteca": 92250 },
  { "nombre": "Australia", "iso3": "AUS", "manteca": 83212 },
  { "nombre": "Dinamarca", "iso3": "DNK", "manteca": 72700 },
  { "nombre": "Japón", "iso3": "JPN", "manteca": 71520 },
  { "nombre": "Ucrania", "iso3": "UKR", "manteca": 67000 },
  { "nombre": "Finlandia", "iso3": "FIN", "manteca": 62680 },
  { "nombre": "Nepal", "iso3": "NPL", "manteca": 61337 },
  { "nombre": "Corea del Sur", "iso3": "KOR", "manteca": 58439 },
  { "nombre": "Tanzania", "iso3": "TZA", "manteca": 50947 },
  { "nombre": "España", "iso3": "ESP", "manteca": 49810 },
  { "nombre": "Myanmar", "iso3": "MMR", "manteca": 49180 },
  { "nombre": "Suiza", "iso3": "CHE", "manteca": 41325 },
  { "nombre": "Afganistán", "iso3": "AFG", "manteca": 41075 },
  { "nombre": "Argentina", "iso3": "ARG", "manteca": 39514 },
  { "nombre": "Suecia", "iso3": "SWE", "manteca": 38690 },
  { "nombre": "Austria", "iso3": "AUT", "manteca": 37910 },
  { "nombre": "Marruecos", "iso3": "MAR", "manteca": 37431 },
  { "nombre": "Bangladesh", "iso3": "BGD", "manteca": 32193 },
  { "nombre": "Portugal", "iso3": "PRT", "manteca": 31870 },
  { "nombre": "Chile", "iso3": "CHL", "manteca": 28973 },
  { "nombre": "Chequia", "iso3": "CZE", "manteca": 27980 },
  { "nombre": "Kazajistán", "iso3": "KAZ", "manteca": 26367 },
  { "nombre": "Azerbaiyán", "iso3": "AZE", "manteca": 25839 },
  { "nombre": "México", "iso3": "MEX", "manteca": 24002 },
  { "nombre": "Uruguay", "iso3": "URY", "manteca": 23422 },
  { "nombre": "Níger", "iso3": "NER", "manteca": 22668 },
  { "nombre": "Colombia", "iso3": "COL", "manteca": 22659 },
  { "nombre": "Etiopía", "iso3": "ETH", "manteca": 22405 },
  { "nombre": "Kenia", "iso3": "KEN", "manteca": 17403 },
  { "nombre": "Siria", "iso3": "SYR", "manteca": 17349 },
  { "nombre": "Sudáfrica", "iso3": "ZAF", "manteca": 16107 },
  { "nombre": "Sudán del Sur", "iso3": "SSD", "manteca": 15482 },
  { "nombre": "Lituania", "iso3": "LTU", "manteca": 15180 },
  { "nombre": "Noruega", "iso3": "NOR", "manteca": 15000 },
  { "nombre": "Mongolia", "iso3": "MNG", "manteca": 12541 },
  { "nombre": "Nigeria", "iso3": "NGA", "manteca": 11874 },
  { "nombre": "Eslovaquia", "iso3": "SVK", "manteca": 11080 },
  { "nombre": "Rumanía", "iso3": "ROU", "manteca": 10220 },
  { "nombre": "Hungría", "iso3": "HUN", "manteca": 9190 },
  { "nombre": "Somalia", "iso3": "SOM", "manteca": 9180 },
  { "nombre": "Costa Rica", "iso3": "CRI", "manteca": 8635 },
  { "nombre": "Túnez", "iso3": "TUN", "manteca": 8621 },
  { "nombre": "Kirguistán", "iso3": "KGZ", "manteca": 8174 },
  { "nombre": "Arabia Saudita", "iso3": "SAU", "manteca": 8013 },
  { "nombre": "Perú", "iso3": "PER", "manteca": 7079 },
  { "nombre": "Honduras", "iso3": "HND", "manteca": 6875 },
  { "nombre": "Yemen", "iso3": "YEM", "manteca": 6607 },
  { "nombre": "Israel", "iso3": "ISR", "manteca": 6503 },
  { "nombre": "Irak", "iso3": "IRQ", "manteca": 6472 },
  { "nombre": "Panamá", "iso3": "PAN", "manteca": 5912 },
  { "nombre": "Estonia", "iso3": "EST", "manteca": 5270 },
  { "nombre": "República de Macedonia", "iso3": "MKD", "manteca": 5195 },
  { "nombre": "Argelia", "iso3": "DZA", "manteca": 4500 },
  { "nombre": "Moldavia", "iso3": "MDA", "manteca": 3836 },
  { "nombre": "Albania", "iso3": "ALB", "manteca": 3811 },
  { "nombre": "Croacia", "iso3": "HRV", "manteca": 3550 },
  { "nombre": "Letonia", "iso3": "LVA", "manteca": 3360 },
  { "nombre": "República Dominicana", "iso3": "DOM", "manteca": 3266 },
  { "nombre": "Tailandia", "iso3": "THA", "manteca": 3002 },
  { "nombre": "Serbia", "iso3": "SRB", "manteca": 2783 },
  { "nombre": "Eslovenia", "iso3": "SVN", "manteca": 2630 },
  { "nombre": "Uganda", "iso3": "UGA", "manteca": 2616 },
  { "nombre": "Islandia", "iso3": "ISL", "manteca": 2612 },
  { "nombre": "Grecia", "iso3": "GRC", "manteca": 2580 },
  { "nombre": "Turkmenistán", "iso3": "TKM", "manteca": 2545 },
  { "nombre": "Ecuador", "iso3": "ECU", "manteca": 2127 },
  { "nombre": "Zimbabue", "iso3": "ZWE", "manteca": 2118 },
  { "nombre": "Bután", "iso3": "BTN", "manteca": 2097 },
  { "nombre": "Ruanda", "iso3": "RWA", "manteca": 1848 },
  { "nombre": "Guatemala", "iso3": "GTM", "manteca": 1756 },
  { "nombre": "Luxemburgo", "iso3": "LUX", "manteca": 1656 },
  { "nombre": "Eritrea", "iso3": "ERI", "manteca": 1620 },
  { "nombre": "Botsuana", "iso3": "BWA", "manteca": 1619 },
  { "nombre": "Burkina Faso", "iso3": "BFA", "manteca": 1611 },
  { "nombre": "Bolivia", "iso3": "BOL", "manteca": 1473 },
  { "nombre": "Emiratos Árabes Unidos", "iso3": "ARE", "manteca": 1370 },
  { "nombre": "Zambia", "iso3": "ZMB", "manteca": 1334 },
  { "nombre": "Omán", "iso3": "OMN", "manteca": 1329 },
  { "nombre": "Sri Lanka", "iso3": "LKA", "manteca": 1202 },
  { "nombre": "Mauritania", "iso3": "MRT", "manteca": 1075 },
  { "nombre": "Bulgaria", "iso3": "BGR", "manteca": 1030 },
  { "nombre": "Senegal", "iso3": "SEN", "manteca": 955 },
  { "nombre": "Paraguay", "iso3": "PRY", "manteca": 900 },
  { "nombre": "Nicaragua", "iso3": "NIC", "manteca": 900 },
  { "nombre": "Angola", "iso3": "AGO", "manteca": 583 },
  { "nombre": "Cuba", "iso3": "CUB", "manteca": 563 },
  { "nombre": "Fiyi", "iso3": "FJI", "manteca": 532 },
  { "nombre": "Montenegro", "iso3": "MNE", "manteca": 515 },
  { "nombre": "Chad", "iso3": "TCD", "manteca": 503 },
  { "nombre": "Namibia", "iso3": "NAM", "manteca": 495 },
  { "nombre": "Guinea", "iso3": "GIN", "manteca": 451 },
  { "nombre": "Armenia", "iso3": "ARM", "manteca": 414 },
  { "nombre": "Georgia", "iso3": "GEO", "manteca": 383 },
  { "nombre": "República de El Salvador", "iso3": "SLV", "manteca": 377 },
  { "nombre": "Burundi", "iso3": "BDI", "manteca": 325 },
  { "nombre": "Bosnia y Herzegovina", "iso3": "BIH", "manteca": 264 },
  { "nombre": "Suazilandia", "iso3": "SWZ", "manteca": 210 },
  { "nombre": "Venezuela", "iso3": "VEN", "manteca": 198 },
  { "nombre": "Sudán", "iso3": "SDN", "manteca": 181 },
  { "nombre": "Taiwán", "iso3": "TWN", "manteca": 124 },
  { "nombre": "Chipre", "iso3": "CYP", "manteca": 40 },
  { "nombre": "Surinam", "iso3": "SUR", "manteca": 25 },
  { "nombre": "Tayikistán", "iso3": "TJK", "manteca": 24 },
  { "nombre": "Togo", "iso3": "TGO", "manteca": 15 },
  { "nombre": "Malta", "iso3": "MLT", "manteca": 0 },
  { "nombre": "Jordania", "iso3": "JOR", "manteca": 0 }
];