    let produccionDeMantecaPorPais = [  
    { "nombre": "India", "manteca": 4883981 },
  { "nombre": "Pakistán", "manteca": 1222785 },
  { "nombre": "Estados Unidos de América", "manteca": 984271 },
  { "nombre": "Alemania", "manteca": 497300 },
  { "nombre": "Nueva Zelanda", "manteca": 483859 },
  { "nombre": "Francia", "manteca": 417540 },
  { "nombre": "Irlanda", "manteca": 293900 },
  { "nombre": "Turquía", "manteca": 270303 },
  { "nombre": "Federación Rusa", "manteca": 269216 },
  { "nombre": "Polonia", "manteca": 243390 },
  { "nombre": "Países Bajos", "manteca": 220710 },
  { "nombre": "Irán", "manteca": 210024 },
  { "nombre": "Reino Unido", "manteca": 200000 },
  { "nombre": "Bélgica", "manteca": 122830 },
  { "nombre": "Bielorrusia", "manteca": 119530 },
  { "nombre": "Canadá", "manteca": 118235 },
  { "nombre": "Brasil", "manteca": 113000 },
  { "nombre": "República Popular China", "manteca": 98294 },
  { "nombre": "Egipto", "manteca": 97714 },
  { "nombre": "Uzbekistán", "manteca": 95822 },
  { "nombre": "Italia", "manteca": 92250 },
  { "nombre": "Australia", "manteca": 83212 },
  { "nombre": "Dinamarca", "manteca": 72700 },
  { "nombre": "Japón", "manteca": 71520 },
  { "nombre": "Ucrania", "manteca": 67000 },
  { "nombre": "Finlandia", "manteca": 62680 },
  { "nombre": "Nepal", "manteca": 61337 },
  { "nombre": "Corea del Sur", "manteca": 58439 },
  { "nombre": "Tanzania", "manteca": 50947 },
  { "nombre": "España", "manteca": 49810 },
  { "nombre": "Myanmar", "manteca": 49180 },
  { "nombre": "Suiza", "manteca": 41325 },
  { "nombre": "Afganistán", "manteca": 41075 },
  { "nombre": "Argentina", "manteca": 39514 },
  { "nombre": "Suecia", "manteca": 38690 },
  { "nombre": "Austria", "manteca": 37910 },
  { "nombre": "Marruecos", "manteca": 37431 },
  { "nombre": "Bangladesh", "manteca": 32193 },
  { "nombre": "Portugal", "manteca": 31870 },
  { "nombre": "Chile", "manteca": 28973 },
  { "nombre": "Chequia", "manteca": 27980 },
  { "nombre": "Kazajistán", "manteca": 26367 },
  { "nombre": "Azerbaiyán", "manteca": 25839 },
  { "nombre": "México", "manteca": 24002 },
  { "nombre": "Uruguay", "manteca": 23422 },
  { "nombre": "Níger", "manteca": 22668 },
  { "nombre": "Colombia", "manteca": 22659 },
  { "nombre": "Etiopía", "manteca": 22405 },
  { "nombre": "Kenia", "manteca": 17403 },
  { "nombre": "Siria", "manteca": 17349 },
  { "nombre": "Sudáfrica", "manteca": 16107 },
  { "nombre": "Sudán del Sur", "manteca": 15482 },
  { "nombre": "Lituania", "manteca": 15180 },
  { "nombre": "Noruega", "manteca": 15000 },
  { "nombre": "Mongolia", "manteca": 12541 },
  { "nombre": "Nigeria", "manteca": 11874 },
  { "nombre": "Eslovaquia", "manteca": 11080 },
  { "nombre": "Rumanía", "manteca": 10220 },
  { "nombre": "Hungría", "manteca": 9190 },
  { "nombre": "Somalia", "manteca": 9180 },
  { "nombre": "Costa Rica", "manteca": 8635 },
  { "nombre": "Túnez", "manteca": 8621 },
  { "nombre": "Kirguistán", "manteca": 8174 },
  { "nombre": "Arabia Saudita", "manteca": 8013 },
  { "nombre": "Perú", "manteca": 7079 },
  { "nombre": "Honduras", "manteca": 6875 },
  { "nombre": "Yemen", "manteca": 6607 },
  { "nombre": "Israel", "manteca": 6503 },
  { "nombre": "Irak", "manteca": 6472 },
  { "nombre": "Panamá", "manteca": 5912 },
  { "nombre": "Estonia", "manteca": 5270 },
  { "nombre": "República de Macedonia", "manteca": 5195 },
  { "nombre": "Argelia", "manteca": 4500 },
  { "nombre": "Moldavia", "manteca": 3836 },
  { "nombre": "Albania", "manteca": 3811 },
  { "nombre": "Croacia", "manteca": 3550 },
  { "nombre": "Letonia", "manteca": 3360 },
  { "nombre": "República Dominicana", "manteca": 3266 },
  { "nombre": "Tailandia", "manteca": 3002 },
  { "nombre": "Serbia", "manteca": 2783 },
  { "nombre": "Eslovenia", "manteca": 2630 },
  { "nombre": "Uganda", "manteca": 2616 },
  { "nombre": "Islandia", "manteca": 2612 },
  { "nombre": "Grecia", "manteca": 2580 },
  { "nombre": "Turkmenistán", "manteca": 2545 },
  { "nombre": "Ecuador", "manteca": 2127 },
  { "nombre": "Zimbabue", "manteca": 2118 },
  { "nombre": "Bután", "manteca": 2097 },
  { "nombre": "Ruanda", "manteca": 1848 },
  { "nombre": "Guatemala", "manteca": 1756 },
  { "nombre": "Luxemburgo", "manteca": 1656 },
  { "nombre": "Eritrea", "manteca": 1620 },
  { "nombre": "Botsuana", "manteca": 1619 },
  { "nombre": "Burkina Faso", "manteca": 1611 },
  { "nombre": "Bolivia", "manteca": 1473 },
  { "nombre": "Emiratos Árabes Unidos", "manteca": 1370 },
  { "nombre": "Zambia", "manteca": 1334 },
  { "nombre": "Omán", "manteca": 1329 },
  { "nombre": "Sri Lanka", "manteca": 1202 },
  { "nombre": "Mauritania", "manteca": 1075 },
  { "nombre": "Bulgaria", "manteca": 1030 },
  { "nombre": "Senegal", "manteca": 955 },
  { "nombre": "Paraguay", "manteca": 900 },
  { "nombre": "Nicaragua", "manteca": 900 },
  { "nombre": "Angola", "manteca": 583 },
  { "nombre": "Cuba", "manteca": 563 },
  { "nombre": "Fiyi", "manteca": 532 },
  { "nombre": "Montenegro", "manteca": 515 },
  { "nombre": "Chad", "manteca": 503 },
  { "nombre": "Namibia", "manteca": 495 },
  { "nombre": "Guinea", "manteca": 451 },
  { "nombre": "Armenia", "manteca": 414 },
  { "nombre": "Georgia", "manteca": 383 },
  { "nombre": "República de El Salvador", "manteca": 377 },
  { "nombre": "Burundi", "manteca": 325 },
  { "nombre": "Bosnia y Herzegovina", "manteca": 264 },
  { "nombre": "Suazilandia", "manteca": 210 },
  { "nombre": "Venezuela", "manteca": 198 },
  { "nombre": "Sudán", "manteca": 181 },
  { "nombre": "Taiwán", "manteca": 124 },
  { "nombre": "Chipre", "manteca": 40 },
  { "nombre": "Surinam", "manteca": 25 },
  { "nombre": "Tayikistán", "manteca": 24 },
  { "nombre": "Togo", "manteca": 15 },
  { "nombre": "Malta", "manteca": 0 },
  { "nombre": "Jordania", "manteca": 0 }]